# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Bindings for normal mode
config.bind(';;', 'set downloads.location.directory ~/Downloads ;; hint links download')
config.bind(';D', 'set downloads.location.directory ~/Downloads ;; hint images download')

# Set Aliases
c.aliases = {
    "q" : "close",
    "qa" : "quit",
    "w" : "session-save",
    "wq" : "quit --save",
    "wqa" : "quit --save",
    "re" : "restart",
}

# Set Default Page
c.url.default_page = "https://www.google.com"

# Set Start Pages
c.url.start_pages = "https://www.google.com"

# Search Engine Setting
c.url.searchengines = {
    "DEFAULT" : "https://www.google.com.ar/search?q={}",
    "ar" : "https://wiki.archlinux.org/index.php/{}",
    "yt" : "https://www.youtube.com/results?search_query={}",
    "=" : "https://www.wolframalpha.com/input/?i={}",
    "ct" : "https://www.ctan.org/search?phrase={}",
    "lg" : "http://gen.lib.rus.ec/search.php?req={}&lg_topic=libgen&open=0&view=simple&res=25&phrase=1&column=def",
    "ha" : "https://hoogle.haskell.org/?hoogle={}",
}
