#! /bin/sh

# A number of packages to update
update_package() { \
    echo "Update : $(checkupdates | wc -l)"
}

# Display the volume
volume() { \
    curVol=$(pacmd list-sinks | grep 'volume:' | grep -E -v 'base volume:' | awk '{print $5}' | tr -d '%' | tail -n 1)
    isMuted=$(pacmd list-sinks | grep 'muted:' | awk '{print $2}' | tail -n 1)
    if [[ $isMuted = 'yes' ]]; then
        echo "  "
    elif [[ $curVol -gt 66 ]] || [[ $curVol -eq 66 ]]; then
        echo "  $curVol%"
    elif [[ $curVol -lt 66 ]] && ([[ $curVol -gt 20 ]] || [[ $curVol -eq 20 ]]); then
        echo "  $curVol%"
    else
        echo "  $curVol%"
    fi
}

# Battery notification
battery() { \
    isCharging=$(acpi -b | grep -o "Charging")
    persentage=$(acpi -b | awk '{print $4}' | tr -d '%,')
    if [[ $isCharging = 'Charging' ]]; then
        echo -e " $persentage%"
    else
        case "$persentage" in
            100|9[0-9]) echo " $persentage%";;
            8[0-9]|7[0-9]) echo " $persentage%";;
            6[0-9]|5[0-9]) echo " $persentage%";;
            4[0-9]|3[0-9]) echo " $persentage%";;
            2[0-9]|1[8-9]) echo " $persentage%";;
            1[0-7]) echo " $persentage%";;
            *) echo " $persentage%";;
        esac
    fi
}

# Monior brightness
brightness() { \
    backlight=$(xbacklight -get | awk -F . '{print $1}')
    case "$backlight" in
        100|9[0-9]|8[0-9]) echo "🌑";;
        7[0-9]|6[0-9]) echo "🌒";;
        5[0-9]|4[0-9]) echo "🌓";;
        3[0-9]|2[0-9]) echo "🌔";;
        *) echo "🌕";;
    esac
}

# Bluetooth Connection
bluetooth() {
    if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]
    then
      echo ""
    else
      if [ $(echo info | bluetoothctl | grep 'Device' | wc -c) -eq 0 ]
      then
        echo " Powered"
      else
        echo " Connected"
      fi
    fi
}

# Network (wifi) Connection
network() { \
    isConnected=$(nmcli -a | grep -v "p2p" | grep "wlp2s0:" | awk '{print $2}')
    ntname=$(nmcli d wifi list | grep "*" | awk '{print $3}')
    ntamount=$(nmcli d wifi list | grep "*" | awk '{print $8}')
    if [[ $isConnected = 'disconnected' ]]; then
        echo -e "Disconnected"
    else
        case "$ntamount" in
            100|9[0-9]) echo "$ntname  😈";;
            8[0-9]|7[0-9]|6[0-9]) echo "$ntname  😃";;
            6[0-9]|5[0-9]) echo "$ntname  😊";;
            4[0-9]|3[0-9]) echo "$ntname  😒";;
            2[0-9]) echo "$ntname  😠";;
            *) echo "$ntname  😱";;
        esac
    fi
}

# Display the date
timedate() { \
    date=$(date '+%Y-%m-%d')
    time=$(date '+%p %l:%M')
    echo "   $time  |     $date"
}

while true; do
    xsetroot -name "| $(update_package) | $(brightness) | $(network) | $(bluetooth) |  $(volume)  | $(battery) |  $(timedate)"
    sleep 5s
done
