#! /bin/bash

BATTINFO=`acpi -b`
while true; do
    if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 5 -d " "` < 00:15:00 ]] ; then
        DISPLAY=:0.0 /usr/bin/notify-send --urgency=critical "low battery" "$BATTINFO"
    fi
    sleep 20
done
