#! /bin/sh

# Display the volume
volume() { \
    curVol=$(pacmd list-sinks | grep 'volume:' | grep -E -v 'base volume:' | awk '{print $5}' | tr -d '%' | tail -n 1)
    isMuted=$(pacmd list-sinks | grep 'muted:' | awk '{print $2}' | tail -n 1)
    if [[ $isMuted = 'yes' ]]; then
        echo -e "  "
    elif [[ $curVol -gt 66 ]] || [[ $curVol -eq 66 ]]; then
        echo -e "  $curVol%"
    elif [[ $curVol -lt 66 ]] && ([[ $curVol -gt 20 ]] || [[ $curVol -eq 20 ]]); then
        echo -e "  $curVol%"
    else
        echo -e "  $curVol%"
    fi
}

battery() { \
    isCharging=$(acpi -b | grep -o "Charging")
    persentage=$(acpi -b | awk '{print $4}' | tr -d '%,')
    if [[ $isCharging = 'Charging' ]]; then
        echo -e " $persentage%"
    else
        case "$persentage" in
            100|9[0-9]) echo -e " $persentage%";;
            8[0-9]|7[0-9]) echo -e " $persentage%";;
            6[0-9]|5[0-9]) echo -e " $persentage%";;
            4[0-9]|3[0-9]) echo -e " $persentage%";;
            2[0-9]|1[8-9]) echo -e " $persentage%";;
            1[0-7]) echo -e " $persentage%";;
            *) echo -e " $persentage%";;
        esac
    fi
}

brightness() { \
    backlight=$(xbacklight -get | awk -F . '{print $1}')
    case "$backlight" in
        100|9[0-9]|8[0-9]) echo -e "🌑";;
        7[0-9]|6[0-9]) echo -e "🌒";;
        5[0-9]|4[0-9]) echo -e "🌓";;
        3[0-9]|2[0-9]) echo -e "🌔";;
        *) echo -e "🌕";;
    esac
}

bluetooth() {
    if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]
    then
      echo -e ""
    else
      if [ $(echo info | bluetoothctl | grep 'Device' | wc -c) -eq 0 ]
      then
        echo -e " Powered"
      else
        echo -e " Connected"
      fi
    fi
}


network() { \
    isConnected=$(nmcli -a | grep -v "p2p" | grep "wlp2s0:" | awk '{print $2}')
    ntname=$(nmcli d wifi list | grep "*" | awk '{print $3}')
    ntamount=$(nmcli d wifi list | grep "*" | awk '{print $8}')
    if [[ $isConnected = 'disconnected' ]]; then
        echo -e "Disconnected"
    else
        case "$ntamount" in
            100|9[0-9]) echo -e "$ntname  😈";;
            8[0-9]|7[0-9]|6[0-9]) echo -e "$ntname  😃";;
            6[0-9]|5[0-9]) echo -e "$ntname  😊";;
            4[0-9]|3[0-9]) echo -e "$ntname  😒";;
            2[0-9]) echo -e "$ntname  😠";;
            *) echo -e "$ntname  😱";;
        esac
    fi
}

# Display the date
timedate() { \
    date=$(date '+%Y-%m-%d')
    time=$(date '+%p %l:%M')
    echo -e "   $time  |     $date"
}

while true; do
    xsetroot -name "| $(brightness) | $(network) | $(bluetooth) |  $(volume)  | $(battery) |  $(timedate)"
    sleep 5s
done
