#!/bin/zsh
scrot /tmp/screen.png
convert /tmp/screen.png -paint 2 /tmp/screen.png
[[ -f ~/GDrive/backup/xmonad/lock.png ]] && convert /tmp/screen.png ~/GDrive/backup/xmonad/lock.png -gravity center -composite -matte /tmp/screen.png
i3lock -e -i /tmp/screen.png
